---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: elastic-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv-volume
  labels:
    type: local
spec:
  storageClassName: elastic-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/etc/plz-k8s-lab/elastic/data/'
