---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: neo4j-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-pv-volume
  labels:
    type: local
spec:
  storageClassName: neo4j-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/etc/plz-k8s-lab/neo4j/data/'
