storageClass: vault-storage

server:
  affinity: ''
  ha:
    replicas: 1
  dataStorage:
    enabled: true
    size: 1Gi
    mountPath: '/etc/plz-k8s-lab/vault/data/'
    storageClass: vault-storage
    accessMode: ReadWriteOnce
    annotations: {}

ui:
  enabled: true
