---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cartography

commonLabels:
  app: cartography
  component: neo4j

resources:
  - vault-agent-sa.yaml
  - neo4j-service.yaml
  - neo4j-statefulset.yaml
