---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cartography-run
  labels:
    app: cartography
    component: cartography
spec:
  schedule: "0 7 * * *" # Run every day at 7am
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 5
      template:
        metadata:
          labels:
            app: cartography
            component: cartography
        spec:
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            runAsUser: 27100
            runAsGroup: 27100
          containers:
            - name: cartography-run
              securityContext:
                allowPrivilegeEscalation: false
              env:
                - name: NEO4J_URI
                  value: "bolt://neo4j-bolt-service:7687"
                - name: NEO4J_USER
                  value: "neo4j"
                - name: AWS_DEFAULT_REGION
                  value: "eu-west-1"
                - name: AWS_DEFAULT_OUTPUT
                  value: "json"
                - name: AWS_DEFAULT_PROFILE
                  value: "default"
              command:
                - "/bin/sh"
                - "-c"
                - |
                - name: aws-accounts-configmap-volume
                  mountPath: /opt/aws-config
                  readOnly: true
            - name: aws-accounts-configmap-volume
              configMap:
                name: aws-accounts-configmap
