---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cartography-run
  namespace: cartography
  labels:
    app: cartography
    component: cartography
spec:
  schedule: '0 7 * * *' # Run every day at 7am
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 5
      template:
        metadata:
          labels:
            app: cartography
            component: cartography
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'vault-agent'
            #
            # AWS CREDENTIALS FROM VAULT
            #
            # ID
            vault.hashicorp.com/agent-inject-secret-aws-security-reviewer-id: 'secret/data/cartography/aws-security-reviewer/aws_access_key_id'
            vault.hashicorp.com/agent-inject-template-aws-security-reviewer-id: |
              {{ with secret "secret/data/cartography/aws-security-reviewer" -}}
                aws_access_key_id="{{ .Data.data.aws_access_key_id }}"
              {{- end }}
            # KEY
            vault.hashicorp.com/agent-inject-secret-aws-security-reviewer-key: 'secret/data/cartography/aws-security-reviewer/aws_secret_access_key'
            vault.hashicorp.com/agent-inject-template-aws-security-reviewer-key: |
              {{ with secret "secret/data/cartography/aws-security-reviewer" -}}
                aws_secret_access_key="{{ .Data.data.aws_secret_access_key }}"
              {{- end }}
            ## END OF CREDENTIALS SETUP
        spec:
          serviceAccountName: vault-agent
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            runAsUser: 27100
            runAsGroup: 27100
          containers:
            - name: cartography-run
              image: //components/cartography:cartography_docker
              securityContext:
                allowPrivilegeEscalation: false
              env:
                - name: NEO4J_URI
                  value: 'bolt://neo4j-bolt-service:7687'
                - name: NEO4J_USER
                  value: 'neo4j'
                - name: AWS_DEFAULT_REGION
                  value: 'eu-west-1'
                - name: AWS_DEFAULT_OUTPUT
                  value: 'json'
                - name: AWS_DEFAULT_PROFILE
                  value: 'default'
              command:
                - '/bin/sh'
                - '-c'
                - |
                - name: aws-accounts-configmap-volume
                  mountPath: /opt/aws-config
                  readOnly: true
            - name: aws-accounts-configmap-volume
              configMap:
                name: aws-accounts-configmap
