---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cartography
commonLabels:
  app: cartography
  component: cartography
resources:
  - aws-accounts-configmap.yaml
  - cartography-job.yaml
