apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  nodeSets:
    - name: default
      count: 1
      podTemplate:
        spec:
          volumes:
            - name: elasticsearch-data
              emptyDir: {}
